### ISSUE TITLE
Problem looting / HOWTO

### ISSUE THREAD

**Issue by mikkosaarinen** [rinnocenti/innocenti-looting#4]
Thank you for the module. I run into some problems partially because I couldn't at first figure out how it should work :D

1. Do I need to manually turn every dead enemy in to loot sheet and give players access to them?
   
Took me a long time to actually figure out how my player can access the loot sheet in the first place, before I understood that I need to switch the sheet to loot sheet. Is there a setting (didn't find) or macro to do this automatically when enemies die?

2. I get an error for no active GM present when trying to loot the enemies.

After getting to the loot sheet, I tried to split the gold three ways and was instantly given a message that there is no active GM on your scene. I have a GM session running in my Foundry VTT app, like always, and was testing this module as a player in Chrome. I can see the GM logged in the lower left hand corner and if I open a new connection to the game, I can see that the GM option has been grayed out, so the game recognizes that there is an active GM connection, so what could be the root of this error?

![image](https://user-images.githubusercontent.com/20413615/107145686-fb07fb00-694b-11eb-9c59-4b281b679c4b.png)

**Comment by rinnocenti** [comment]
I should prepare a video about the module to help with these parts, because it is simpler than people think it is.
I'll make a video to be clearer, but in advance
1- No. You don't need to change the file, you don't need to give authorization or anything. (maybe this is the reason for the second question)

2- It is probably due to the use of the module, it is very simple. but explaining something simple is usually laborious and I think a video works better.

I will record one in the next few days

**Comment by rinnocenti** [comment]
I make a video (in my original language, but have legend)
https://www.youtube.com/watch?v=v6JPQ9MWi4U
